latest

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -6,15 +6,16 @@ on:
 jobs:
   echo-hello:
     runs-on: ubuntu-latest
-      steps: 
-        - name: Say Hello
-          run: echo "Hello World!"
+    steps: 
+      - name: Say Hello
+        run: echo "Hello World!"
   echo-goodbye:
     runs-on: ubuntu-latest
-        - name: Failed Step
-          run: |
-            echo "I will fail!"
-            exit 1
-        - name: Say Goodbye
-          run: echo "Goodbye!"
+    steps:
+      - name: Failed Step
+        run: |
+          echo "I will fail!"
+          exit 1
+      - name: Say Goodbye
+        run: echo "Goodbye!"
 
